export const validationRules = (isEdit) => ({
    carNamePl: { required: true },
    categoryId: { required: true },
    manufactureYear: { required: true, min: 0 },
    askingPrice: { required: true, min: 0, pattern: /^\d+(\.\d{1,2})?$/ },
    mileage: { required: true, min: 0, pattern: /^\d+$/ },
    warrantyIsAvailable: { required: true },
    colorExterior: { required: true },
    colorInterior: { required: true },
    exteriorColorNamePl: { required: true },
    interiorColorNamePl: { required: true },
    // technicalDescriptionPl: { required: true },
    // technicalDescriptionSl: { required: true },
    // plateNumber: { required: true },
    // chassisNumber: { required: true },
    ownerName: { required: true },
    ownerMobile: { required: true },
    minimumPrice: { required: true,  pattern: /^\d+(\.\d{1,2})?$/ },
  });